version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2ws3ed
      POSTGRES_DB: telegram_bot_subscriptions
    ports:
      - "5555:5432"